### ISSUE TITLE
Can't run on mac machine

### ISSUE THREAD

**Issue by rluvaton** [HliasOuzounis/Ai-Guess-the-elo#1]
When I try running on my macbook pro m1 I get the following:
```
❯ python3 guess_the_elo.py --engine=`which stockfish` /tmp/test-game.pgn
Analyzing game: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 118/118 [00:21<00:00,  5.38it/s]
Traceback (most recent call last):
  File "/Users/rluvaton/dev/tmp/Ai-Guess-the-elo/guess_the_elo.py", line 111, in <module>
    main()
  File "/Users/rluvaton/dev/tmp/Ai-Guess-the-elo/guess_the_elo.py", line 69, in main
    predictions = predict_game(
                  ^^^^^^^^^^^^^
  File "/Users/rluvaton/dev/tmp/Ai-Guess-the-elo/guess_the_elo.py", line 85, in predict_game
    predictions = get_ai_prediction(
                  ^^^^^^^^^^^^^^^^^^
  File "/Users/rluvaton/dev/tmp/Ai-Guess-the-elo/guess_the_elo.py", line 95, in get_ai_prediction
    model = load_model()
            ^^^^^^^^^^^^
  File "/Users/rluvaton/dev/tmp/Ai-Guess-the-elo/guess_the_elo.py", line 48, in load_model
    model.load_state_dict(torch.load(
                          ^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/serialization.py", line 1116, in load_tensor
    wrap_storage=restore_location(storage, location),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/serialization.py", line 217, in default_restore_location
    result = fn(storage, location)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/serialization.py", line 166, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

I tried adding `, map_location='cpu'` to `torch.load` as suggested in the error message but the same result, so I wanted to train the model again but the data set seems to be missing

**Comment by rluvaton** [comment]
my bad I did not put the map location at the right place
